kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: k8s-secrets-account
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: k8s-secrets-account-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
 kind: Role
 name: k8s-secrets-account
 apiGroup: rbac.authorization.k8s.io
